services:
  redis:
    image: redis:alpine
    container_name: t_invest_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: t_invest_backend
    restart: unless-stopped
    command: >
      sh -c "python backend/manage.py migrate &&
             python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: t_invest_worker
    restart: unless-stopped
    command: celery --workdir backend -A config worker --loglevel=info
    volumes:
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
      - ./backend:/app/backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
      - backend

  celery_beat:
    build: .
    container_name: t_invest_beat
    restart: unless-stopped
    command: celery --workdir backend -A config beat --loglevel=info
    volumes:
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
      - ./backend:/app/backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
      - backend

  bot:
    build: .
    container_name: t_invest_bot
    restart: unless-stopped
    network_mode: "host"
    command: python -m bot.main
    volumes:
      - ./bot:/app/bot
    environment:
      - BACKEND_URL=http://127.0.0.1:8000
    env_file:
      - .env
    depends_on:
      - backend
