# Generated by Django 6.1.1 on 2026-09-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoruser',
            name='active_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.account'),
        ),
        migrations.AlterField(
            model_name='investoruser',
            name='encrypted_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.CreateModel(
            name='BrokerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной токен', max_length=64)),
                ('encrypted_token', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_tokens', to='users.investoruser')),
            ],
        ),
    ]
