# Generated by Django 6.1.1 on 2026-09-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_investoruser_active_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoruser',
            name='alerts_enabled',
            field=models.BooleanField(default=True, verbose_name='Включены ли риск-алерты'),
        ),
    ]
