# Generated by Django 6.1.1 on 2026-09-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_investoruser_alerts_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="investoruser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("retail", "Частный инвестор"),
                    ("pro", "Бизнес / Профессионал"),
                ],
                default="retail",
                help_text="retail - частный инвестор, pro - бизнес / профессиональный инвестор",
                max_length=20,
                verbose_name="Тип инвестора",
            ),
        ),
    ]
