# Generated by Django 6.1.1 on 2026-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_investoruser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="investoruser",
            name="user_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC-SHA256 от telegram_id с секретной солью для анонимизации",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Хэш пользователя (Zero-Knowledge ID)",
            ),
        ),
    ]
