# Generated by Django 6.1.1 on 2026-09-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=128)),
                ("account_type", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="users.investoruser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "total_amount_portfolio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "total_amount_shares",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "total_amount_bonds",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "total_amount_etf",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "total_amount_currencies",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "expected_yield",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="portfolio.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("figi", models.CharField(db_index=True, max_length=64)),
                ("ticker", models.CharField(blank=True, max_length=32)),
                ("name", models.CharField(blank=True, max_length=256)),
                ("instrument_type", models.CharField(max_length=32)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("current_price", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "average_position_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "expected_yield",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="portfolio.portfoliosnapshot",
                    ),
                ),
            ],
        ),
    ]
