# Generated by Django 6.1.1 on 2026-09-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('users', '0002_investoruser_active_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='broker_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.brokertoken'),
        ),
    ]
