# Generated by Django 6.1.1 on 2026-09-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_account_broker_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliosnapshot",
            name="positions_pruned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="portfoliosnapshot",
            index=models.Index(
                fields=["account", "-created_at"], name="ps_account_created_idx"
            ),
        ),
    ]
